//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greenmarks.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bma_fullsendpromotions
    {
        public int pmid { get; set; }
        public int storeid { get; set; }
        public System.DateTime starttime { get; set; }
        public System.DateTime endtime { get; set; }
        public short userranklower { get; set; }
        public byte state { get; set; }
        public string name { get; set; }
        public int limitmoney { get; set; }
        public int addmoney { get; set; }
    }
}
