//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greenmarks.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bma_storeshipfees
    {
        public int recordid { get; set; }
        public int storestid { get; set; }
        public int regionid { get; set; }
        public int startvalue { get; set; }
        public int startfee { get; set; }
        public int addvalue { get; set; }
        public int addfee { get; set; }
    }
}
