//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greenmarks.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bma_friendlinks
    {
        public int id { get; set; }
        public string name { get; set; }
        public string title { get; set; }
        public string logo { get; set; }
        public string url { get; set; }
        public int target { get; set; }
        public int displayorder { get; set; }
    }
}
