//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greenmarks.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bma_adverts
    {
        public int adid { get; set; }
        public int clickcount { get; set; }
        public short adposid { get; set; }
        public byte state { get; set; }
        public System.DateTime starttime { get; set; }
        public System.DateTime endtime { get; set; }
        public int displayorder { get; set; }
        public string title { get; set; }
        public string image { get; set; }
        public string url { get; set; }
        public string extfield1 { get; set; }
        public string extfield2 { get; set; }
        public string extfield3 { get; set; }
        public string extfield4 { get; set; }
        public string extfield5 { get; set; }
    }
}
