//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greenmarks.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bma_coupons
    {
        public int couponid { get; set; }
        public string couponsn { get; set; }
        public int uid { get; set; }
        public int coupontypeid { get; set; }
        public int storeid { get; set; }
        public int oid { get; set; }
        public System.DateTime usetime { get; set; }
        public string useip { get; set; }
        public int money { get; set; }
        public System.DateTime activatetime { get; set; }
        public string activateip { get; set; }
        public int createuid { get; set; }
        public int createoid { get; set; }
        public System.DateTime createtime { get; set; }
        public string createip { get; set; }
    }
}
