//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greenmarks.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bma_productconsults
    {
        public int consultid { get; set; }
        public int pid { get; set; }
        public byte consulttypeid { get; set; }
        public byte state { get; set; }
        public int consultuid { get; set; }
        public int replyuid { get; set; }
        public int storeid { get; set; }
        public System.DateTime consulttime { get; set; }
        public System.DateTime replytime { get; set; }
        public string consultmessage { get; set; }
        public string replymessage { get; set; }
        public string consultnickname { get; set; }
        public string replynickname { get; set; }
        public string pname { get; set; }
        public string pshowimg { get; set; }
        public string consultip { get; set; }
        public string replyip { get; set; }
    }
}
