//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greenmarks.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bma_shipaddresses
    {
        public int said { get; set; }
        public int uid { get; set; }
        public short regionid { get; set; }
        public byte isdefault { get; set; }
        public string alias { get; set; }
        public string consignee { get; set; }
        public string mobile { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string zipcode { get; set; }
        public string address { get; set; }
    }
}
