//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greenmarks.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bma_productreviews
    {
        public int reviewid { get; set; }
        public int pid { get; set; }
        public int uid { get; set; }
        public int oprid { get; set; }
        public int oid { get; set; }
        public int parentid { get; set; }
        public byte state { get; set; }
        public int storeid { get; set; }
        public byte star { get; set; }
        public short quality { get; set; }
        public string message { get; set; }
        public System.DateTime reviewtime { get; set; }
        public int paycredits { get; set; }
        public string pname { get; set; }
        public string pshowimg { get; set; }
        public System.DateTime buytime { get; set; }
        public string ip { get; set; }
    }
}
