//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greenmarks.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bma_orderproducts
    {
        public int recordid { get; set; }
        public int oid { get; set; }
        public int uid { get; set; }
        public string sid { get; set; }
        public int pid { get; set; }
        public string psn { get; set; }
        public short cateid { get; set; }
        public int brandid { get; set; }
        public int storeid { get; set; }
        public int storecid { get; set; }
        public int storestid { get; set; }
        public string name { get; set; }
        public string showimg { get; set; }
        public decimal discountprice { get; set; }
        public decimal shopprice { get; set; }
        public decimal costprice { get; set; }
        public decimal marketprice { get; set; }
        public int weight { get; set; }
        public byte isreview { get; set; }
        public int realcount { get; set; }
        public int buycount { get; set; }
        public int sendcount { get; set; }
        public byte type { get; set; }
        public int paycredits { get; set; }
        public int coupontypeid { get; set; }
        public int extcode1 { get; set; }
        public int extcode2 { get; set; }
        public int extcode3 { get; set; }
        public int extcode4 { get; set; }
        public int extcode5 { get; set; }
        public System.DateTime addtime { get; set; }
    }
}
