//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greenmarks.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bma_attributes
    {
        public short attrid { get; set; }
        public string name { get; set; }
        public short cateid { get; set; }
        public short attrgroupid { get; set; }
        public byte showtype { get; set; }
        public byte isfilter { get; set; }
        public int displayorder { get; set; }
    }
}
