//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greenmarks.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bma_attributevalues
    {
        public int attrvalueid { get; set; }
        public string attrvalue { get; set; }
        public byte isinput { get; set; }
        public string attrname { get; set; }
        public int attrdisplayorder { get; set; }
        public byte attrshowtype { get; set; }
        public int attrvaluedisplayorder { get; set; }
        public short attrgroupid { get; set; }
        public string attrgroupname { get; set; }
        public int attrgroupdisplayorder { get; set; }
        public short attrid { get; set; }
    }
}
