//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greenmarks.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bma_stores
    {
        public int storeid { get; set; }
        public byte state { get; set; }
        public string name { get; set; }
        public short regionid { get; set; }
        public short storerid { get; set; }
        public short storeiid { get; set; }
        public string logo { get; set; }
        public System.DateTime createtime { get; set; }
        public string mobile { get; set; }
        public string phone { get; set; }
        public string qq { get; set; }
        public string ww { get; set; }
        public decimal depoint { get; set; }
        public decimal sepoint { get; set; }
        public decimal shpoint { get; set; }
        public int honesties { get; set; }
        public System.DateTime stateendtime { get; set; }
        public string theme { get; set; }
        public string banner { get; set; }
        public string announcement { get; set; }
        public string description { get; set; }
    }
}
