//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greenmarks.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bma_orderrefunds
    {
        public int refundid { get; set; }
        public byte state { get; set; }
        public int storeid { get; set; }
        public string storename { get; set; }
        public int oid { get; set; }
        public string osn { get; set; }
        public int uid { get; set; }
        public int asid { get; set; }
        public string paysystemname { get; set; }
        public string payfriendname { get; set; }
        public string paysn { get; set; }
        public decimal paymoney { get; set; }
        public decimal refundmoney { get; set; }
        public System.DateTime applytime { get; set; }
        public string refundsn { get; set; }
        public System.DateTime refundtime { get; set; }
    }
}
