//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greenmarks.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bma_giftpromotions
    {
        public int pmid { get; set; }
        public int pid { get; set; }
        public int storeid { get; set; }
        public System.DateTime starttime1 { get; set; }
        public System.DateTime endtime1 { get; set; }
        public System.DateTime starttime2 { get; set; }
        public System.DateTime endtime2 { get; set; }
        public System.DateTime starttime3 { get; set; }
        public System.DateTime endtime3 { get; set; }
        public short userranklower { get; set; }
        public byte state { get; set; }
        public string name { get; set; }
        public int quotaupper { get; set; }
    }
}
