//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greenmarks.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bma_orderafterservices
    {
        public int asid { get; set; }
        public byte state { get; set; }
        public int uid { get; set; }
        public int oid { get; set; }
        public int recordid { get; set; }
        public int pid { get; set; }
        public short cateid { get; set; }
        public int brandid { get; set; }
        public int storeid { get; set; }
        public string pname { get; set; }
        public string pshowimg { get; set; }
        public int count { get; set; }
        public decimal money { get; set; }
        public byte type { get; set; }
        public string applyreason { get; set; }
        public System.DateTime applytime { get; set; }
        public string checkresult { get; set; }
        public System.DateTime checktime { get; set; }
        public short shipcoid1 { get; set; }
        public string shipconame1 { get; set; }
        public string shipsn1 { get; set; }
        public short regionid { get; set; }
        public string consignee { get; set; }
        public string mobile { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string zipcode { get; set; }
        public string address { get; set; }
        public System.DateTime sendtime { get; set; }
        public System.DateTime receivetime { get; set; }
        public short shipcoid2 { get; set; }
        public string shipconame2 { get; set; }
        public string shipsn2 { get; set; }
        public System.DateTime backtime { get; set; }
    }
}
