//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greenmarks.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bma_creditlogs
    {
        public int logid { get; set; }
        public int uid { get; set; }
        public int paycredits { get; set; }
        public int rankcredits { get; set; }
        public byte action { get; set; }
        public int actioncode { get; set; }
        public System.DateTime actiontime { get; set; }
        public string actiondes { get; set; }
        public int @operator { get; set; }
    }
}
