//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greenmarks.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class brnmallEntities : DbContext
    {
        public brnmallEntities()
            : base("name=brnmallEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bma_advertpositions> bma_advertpositions { get; set; }
        public virtual DbSet<bma_adverts> bma_adverts { get; set; }
        public virtual DbSet<bma_attributegroups> bma_attributegroups { get; set; }
        public virtual DbSet<bma_attributes> bma_attributes { get; set; }
        public virtual DbSet<bma_attributevalues> bma_attributevalues { get; set; }
        public virtual DbSet<bma_bannedips> bma_bannedips { get; set; }
        public virtual DbSet<bma_brands> bma_brands { get; set; }
        public virtual DbSet<bma_browsehistories> bma_browsehistories { get; set; }
        public virtual DbSet<bma_buysendproducts> bma_buysendproducts { get; set; }
        public virtual DbSet<bma_buysendpromotions> bma_buysendpromotions { get; set; }
        public virtual DbSet<bma_categories> bma_categories { get; set; }
        public virtual DbSet<bma_couponproducts> bma_couponproducts { get; set; }
        public virtual DbSet<bma_coupons> bma_coupons { get; set; }
        public virtual DbSet<bma_coupontypes> bma_coupontypes { get; set; }
        public virtual DbSet<bma_creditlogs> bma_creditlogs { get; set; }
        public virtual DbSet<bma_eventlogs> bma_eventlogs { get; set; }
        public virtual DbSet<bma_favoriteproducts> bma_favoriteproducts { get; set; }
        public virtual DbSet<bma_favoritestores> bma_favoritestores { get; set; }
        public virtual DbSet<bma_filterwords> bma_filterwords { get; set; }
        public virtual DbSet<bma_fullcutproducts> bma_fullcutproducts { get; set; }
        public virtual DbSet<bma_fullcutpromotions> bma_fullcutpromotions { get; set; }
        public virtual DbSet<bma_fullsendproducts> bma_fullsendproducts { get; set; }
        public virtual DbSet<bma_fullsendpromotions> bma_fullsendpromotions { get; set; }
        public virtual DbSet<bma_giftpromotions> bma_giftpromotions { get; set; }
        public virtual DbSet<bma_gifts> bma_gifts { get; set; }
        public virtual DbSet<bma_loginfaillogs> bma_loginfaillogs { get; set; }
        public virtual DbSet<bma_malladmingroups> bma_malladmingroups { get; set; }
        public virtual DbSet<bma_malladminlogs> bma_malladminlogs { get; set; }
        public virtual DbSet<bma_news> bma_news { get; set; }
        public virtual DbSet<bma_newstypes> bma_newstypes { get; set; }
        public virtual DbSet<bma_oauth> bma_oauth { get; set; }
        public virtual DbSet<bma_onlinetime> bma_onlinetime { get; set; }
        public virtual DbSet<bma_onlineusers> bma_onlineusers { get; set; }
        public virtual DbSet<bma_orderactions> bma_orderactions { get; set; }
        public virtual DbSet<bma_orderafterservices> bma_orderafterservices { get; set; }
        public virtual DbSet<bma_orderproducts> bma_orderproducts { get; set; }
        public virtual DbSet<bma_orderrefunds> bma_orderrefunds { get; set; }
        public virtual DbSet<bma_orders> bma_orders { get; set; }
        public virtual DbSet<bma_productattributes> bma_productattributes { get; set; }
        public virtual DbSet<bma_productconsults> bma_productconsults { get; set; }
        public virtual DbSet<bma_productconsulttypes> bma_productconsulttypes { get; set; }
        public virtual DbSet<bma_productimages> bma_productimages { get; set; }
        public virtual DbSet<bma_productkeywords> bma_productkeywords { get; set; }
        public virtual DbSet<bma_productreviewquality> bma_productreviewquality { get; set; }
        public virtual DbSet<bma_productreviews> bma_productreviews { get; set; }
        public virtual DbSet<bma_products> bma_products { get; set; }
        public virtual DbSet<bma_productskus> bma_productskus { get; set; }
        public virtual DbSet<bma_productstats> bma_productstats { get; set; }
        public virtual DbSet<bma_productstocks> bma_productstocks { get; set; }
        public virtual DbSet<bma_pvstats> bma_pvstats { get; set; }
        public virtual DbSet<bma_regions> bma_regions { get; set; }
        public virtual DbSet<bma_relateproducts> bma_relateproducts { get; set; }
        public virtual DbSet<bma_searchhistories> bma_searchhistories { get; set; }
        public virtual DbSet<bma_shipaddresses> bma_shipaddresses { get; set; }
        public virtual DbSet<bma_singlepromotions> bma_singlepromotions { get; set; }
        public virtual DbSet<bma_storeadminlogs> bma_storeadminlogs { get; set; }
        public virtual DbSet<bma_storeclasses> bma_storeclasses { get; set; }
        public virtual DbSet<bma_storeindustries> bma_storeindustries { get; set; }
        public virtual DbSet<bma_storekeepers> bma_storekeepers { get; set; }
        public virtual DbSet<bma_storeranks> bma_storeranks { get; set; }
        public virtual DbSet<bma_storereviews> bma_storereviews { get; set; }
        public virtual DbSet<bma_stores> bma_stores { get; set; }
        public virtual DbSet<bma_storeshipfees> bma_storeshipfees { get; set; }
        public virtual DbSet<bma_storeshiptemplates> bma_storeshiptemplates { get; set; }
        public virtual DbSet<bma_suitproducts> bma_suitproducts { get; set; }
        public virtual DbSet<bma_suitpromotions> bma_suitpromotions { get; set; }
        public virtual DbSet<bma_timeproducts> bma_timeproducts { get; set; }
        public virtual DbSet<bma_topics> bma_topics { get; set; }
        public virtual DbSet<bma_userdetails> bma_userdetails { get; set; }
        public virtual DbSet<bma_userranks> bma_userranks { get; set; }
        public virtual DbSet<bma_users> bma_users { get; set; }
        public virtual DbSet<bma_friendlinks> bma_friendlinks { get; set; }
        public virtual DbSet<bma_helps> bma_helps { get; set; }
        public virtual DbSet<bma_malladminactions> bma_malladminactions { get; set; }
        public virtual DbSet<bma_navs> bma_navs { get; set; }
        public virtual DbSet<bma_shipcompanies> bma_shipcompanies { get; set; }
    }
}
